site_name: Deep Symbolic Optimization
site_url: https://your-org.github.io/dso
repo_url: https://github.com/sheydHD/deep-symbolic-optimization
repo_name: sheydHD/deep-symbolic-optimization
edit_uri: edit/modernize-2025/docs/

docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - Overview: overview.md
  - Guides:
      - Installation: guides/installation.md
      - Getting Started: guides/getting_started.md
  - Rules:
      - Code Style: rules/code_style.md
      - Testing Rules: rules/testing_rules.md
      - Git Rules: rules/git_rules.md
      - Branching Model: rules/branching_model.md
      - Docs Rules: rules/docs_rules.md
      - PR Review Rules: rules/pr_review_rules.md
      - Project Structure: rules/project_structure.md
      - Security Rules: rules/security_rules.md
      - Rules Overview: rules/README.md
  - Structure: structure/project_structure.md
  - Tasks:
      - Modernization Plan: tasks/done/modernization_plan.md
      - Modernization Roadmap: tasks/done/modernization_roadmap.md
      - Test Fixes: tasks/done/test_fix.md
      - Upgrade Summary: tasks/done/upgrade_summary.md

theme:
  name: material
  logo: attachments/images/banner.png
  favicon: attachments/images/banner.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - markdownextradata

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sheydHD/deep-symbolic-optimization/tree/modernize-2025
