site_name: Deep Symbolic Optimization
site_url: https://your-org.github.io/dso
repo_url: https://github.com/your-org/dso
repo_name: your-org/dso

docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Overview: overview.md
  - Guides:
      - Installation: guides/installation.md
      - Getting Started: guides/getting_started.md
  - Architecture: architecture/overview.md
  - Reference: reference/api_reference.md
  - Operations:
      - Release Process: operations/release_process.md
  - Rules:
      - Code Style: rules/code_style.md
      - Testing: rules/testing_rules.md
      - Git Rules: rules/git_rules.md
      - Branching Model: rules/branching_model.md
      - Docs Rules: rules/docs_rules.md
  - Legal:
      - Code of Conduct: legal/CODE_OF_CONDUCT.md
      - Security Policy: legal/SECURITY.md

theme:
  name: material
  logo: images/banner.png
  favicon: images/banner.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - markdownextradata

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
